### ISSUE TITLE
instructions to enter bootloader modr on the stm mini esp32?

### ISSUE THREAD

**Issue by guysoft** [STEMinds/STEMinds-Docs#12]
Want to flash something else on it. Some places say to short gpio0 but cant seem to find it.

**Comment by Zontex** [comment]
Hi,Boot loader mode automatically entered due to the CH340 chip configuration - you just need to flash it. What were you trying to do and what error are you getting?On 15 Jan 2024, at 10:30, Guy Sheffer ***@***.***> wrote:﻿
Want to flash something else on it. Some places say to short gpio0 but cant seem to find it.

**Comment by guysoft** [comment]
I wanted to flash something else on it, but I need an esp32-S2 with USB OTG.
Located the boot switch, its not soldered on my board.

**Comment by Zontex** [comment]
You don’t need the boot switch, it’s automatic. S2 is not pin compatible On 16 Jan 2024, at 7:11, Guy Sheffer ***@***.***> wrote:﻿
I wanted to flash something else on it, but I need an esp32-S2 with USB OTG.
Located the boot switch, its not soldered on my board.

**Comment by guysoft** [comment]
I wanted to flash an arduino project. 
https://github.com/nonoo/esp-remote-wakeup

But its not relevant
